// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "Production-ready message scheduler service with automatic webhook delivery, retry mechanism, and Redis caching.",
        "title": "Message Scheduler Service API",
        "contact": {
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "paths": {
        "/messages/sent": {
            "get": {
                "description": "Retrieves a paginated list of sent messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Get sent messages",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sent messages with pagination info",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sender/start": {
            "post": {
                "description": "Starts the automatic message sending scheduler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sender"
                ],
                "summary": "Start scheduler",
                "responses": {
                    "200": {
                        "description": "Scheduler started successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Scheduler is already running",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sender/status": {
            "get": {
                "description": "Returns the current status of the scheduler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sender"
                ],
                "summary": "Get scheduler status",
                "responses": {
                    "200": {
                        "description": "Scheduler status with is_running field",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sender/stop": {
            "post": {
                "description": "Stops the automatic message sending scheduler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sender"
                ],
                "summary": "Stop scheduler",
                "responses": {
                    "200": {
                        "description": "Scheduler stopped successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Scheduler is not running",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Message Scheduler Service API",
	Description:      "Production-ready message scheduler service with automatic webhook delivery, retry mechanism, and Redis caching.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
